### ISSUE TITLE
Replace vis by plantuml for pipeline chains visualization

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#126]
For long chains, the visualization provided by visjs does not seem adapted.

We could use plantuml, the generated graphics are much more readable (and prettier imo).

There's a jquery plugin, that basically generates the preview by calling the plantuml website : http://plantuml.com/jquery

**Comment by jc7447** [comment]
Well, I'm not sure why you are saying that visjs is not adapted ?

As far as I understand, plantuml will generate images on a foreign server and I see several difficulties with that : 
- We will potentially send confidential data to a foreign server :  client name, how the payment/return process works, PSP names, class names and so on...
- We will make BDA dependent to a server that may be down, slow, ... and we have no control over it.

Also since we will have images, we will lose all zoom, navigation, interaction capabilities that we have with vis.js (and we can certainly do better around this).

Big pipeline chains are not easy to render and I'm not 100% sure that the output with plantuml will be more readable, we will probably got a big image or a small one with small fonts. We can test it to see the result but my previous remarks are blocking points for me.

**Comment by troussej** [comment]
yes I 100% agree with those points. It's more an open suggestion to test it.

The real point is : currently big chains are not readable at all. 

And by hand i succesfuly drawn big chains with plantuml (altough they produce big images), so I was wondering if it could be used instead.

**Comment by troussej** [comment]
Closing this as it is replace by #127
