### ISSUE TITLE
[Pipeline] Bug - Visual Representation scale issue

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#52]
When a chain is too long, the visualisation is not very readable, it's crunshed in the small popin. See screenshot with "updateOrder" example.

Tested on chrome Version 48.0.2564.109 m

![2016-02-17 10_44_49-pipelinemanager](https://cloud.githubusercontent.com/assets/8314012/13105506/c806efee-d563-11e5-9a88-e4cade04b87d.png)

**Comment by jc7447** [comment]
I think, you are not using the proper version of the CSS file because tampermonkey hasn't download it for some reason (it's an issue we encounter elsewhere)

Please reinstall the script to refresh the CSS, the pop-in should be 90% of the size of the window.

You can also zoom with the scroll button, and drag into the popin to have a closer look. If it is still to small, let me know :)

**Comment by troussej** [comment]
ok it works. it's still small but the zoom works.

Maybe you could add a minimal size for the proc boxes.
