### ISSUE TITLE
[CSS/JS] bootstrap?

### ISSUE THREAD

**Issue by troussej** [jc7447/BetterDynAdmin#71]
JC,

Do you seen any issue about adding some external js/css library, like boostrap for example, instead of doing everything by hand? I think it would greatly simplify the development of new panels/popins. 

Especially since i'm a css n00b :P

**Comment by jc7447** [comment]
Bootstrap is a great tool for sure, but when I started BDA I wasn't thinking about redesign dyn/admin pages. Not that I think it shouldn't be done ! But I think it shouldn't be done by BDA because the userscript approach will cause, I think, sooner or later performance issue.

I already saw that in Chrome there can be a real latency between the rendering of the page and the rendering of BDA, with a blink effect. I'm afraid this latency can increase with bootstrap or other similar tools.

Do you think we will need more than the modal component soon in BDA ? If not, may be we can look at a simple jquery plugin to help us with popin.

There is a way to get a custom bootstrap package with only the stuff we need, may be we can begin with a very light bootstrap package and add new component when we need it.

**Comment by troussej** [comment]
Yeah I totally get your point.

It's just that I was struggling to add some new elements on the fav bar
(float/clear placements.. arg!) . I think it's more the css that I need,
instead of the js.


--
 Joël Trousset
06 73 64 87 79

**Comment by troussej** [comment]
well since #72 bootstrap is included in BDA, but it won't affect the pages - the css is wrapped in a "twbs" class. We might need to check js impacts.
