### ISSUE TITLE
Why do we need to copy findclass.jhtml?

### ISSUE THREAD

**Issue by obedmhg** [jc7447/BetterDynAdmin#95]
Hi Jean,
The Instructions have this step:
Copy ${DYNAMO_ROOT}/home/doc/findclass.jhtml to ${DYNAMO_ROOT}/DAS/admin/atg/dynamo/admin/en/
I do not know why is needed?
Perhaps a change on how the link will make this unnecessary?
from:
``
$("<span style='margin-left : 25px'><a href='/dyn/admin/atg/dynamo/admin/en/findclass.jhtml?className="+className+"&debug=true'>Find Class</a></span>")
        .insertAfter($classLink);
``
to
``
$("<span style='margin-left : 25px'><a href='/dyn/dyn/findclass.jhtml?className="+className+"&debug=true'>Find Class</a></span>")
        .insertAfter($classLink);
``
Please let me know if this is OK, if not please explain me why the copy is needed, I do not understand :(
Regards,
Obed

**Comment by jc7447** [comment]
Hi Obed,

I was actually thinking that /dyn/dyn/findclass.jhtml was not reachable, probably because I was working on a project that just allow /dyn/admin and forbid everything else, when I wrote this.

You're right we should modify the code as you suggest and remove this step from the installation instructions.

I will do it as part of version 2.0 which will be release soon ;)

Thank you :)

**Comment by obedmhg** [comment]
This is great, 

I am using your dev branch already, so I assume I'll get all the good things from the dev branch into 2.0 :)
Thanks for such great job!

Regards,
Obed
